# Generated by Django 3.0.7 on 2020-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('news_class', models.IntegerField(choices=[(2, 'Health'), (5, 'Technology'), (4, 'Economics'), (1, 'Sports'), (3, 'Politics')])),
                ('photo_main', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('photo_more', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('tags', models.TextField()),
                ('published', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(editable=False)),
            ],
        ),
    ]
