# Generated by Django 3.0.7 on 2020-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='news_class',
            field=models.IntegerField(choices=[(4, 'Economics'), (1, 'Sports'), (3, 'Politics'), (5, 'Technology'), (2, 'Health')]),
        ),
        migrations.AlterField(
            model_name='new',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
