# Generated by Django 3.0.7 on 2020-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200726_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='news_class',
        ),
        migrations.AlterField(
            model_name='new',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='news_class',
            field=models.ManyToManyField(to='news.NewsClass'),
        ),
    ]
