# Generated by Django 3.0.7 on 2020-07-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200726_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='photo_more',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
