# Generated by Django 3.0.7 on 2020-07-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200727_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
