# Generated by Django 3.0.7 on 2020-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200727_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
