# Generated by Django 3.0.7 on 2020-07-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200727_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
