# Generated by Django 3.0.7 on 2020-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200727_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
