# Generated by Django 3.0.7 on 2020-07-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField(default='')),
                ('paragraph_3', models.TextField(default='')),
                ('paragraph_4', models.TextField(default='')),
                ('photo_main', models.ImageField(upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
